name: Linux tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  linux:
    name: Linux Py${{ matrix.PYTHON_VERSION }}
    runs-on: ubuntu-latest
    env:
      CI: True
      CODECOV_TOKEN: "a622d5af-356c-41f6-b298-b9b96f75be41"
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      RUNNER_OS: 'ubuntu'
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['3.7', '3.8']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install System Packages
        run: | 
          sudo apt-get update
          sudo apt-get install libegl1-mesa
      - name: Install Conda
        uses: goanpeca/setup-miniconda@v1
        with:
           activate-environment: test
           auto-update-conda: true
           auto-activate-base: false
           python-version: ${{ matrix.PYTHON_VERSION }} 
      - name: Install package dependencies
        shell: bash -l {0}
        run: conda install --file requirements/conda.txt -y -q
      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          conda install nomkl -y -q
          conda install -c spyder-ide --file requirements/tests.txt -y -q
      - name: Install Package
        shell: bash -l {0}
        run: pip install --no-deps -e .
      - name: Show environment information
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Codecov
        uses: codecov/codecov-action@v1.0.14
      - name: Run tests
        shell: bash -l {0}
        run: xvfb-run --auto-servernum python runtests.py
        timeout-minutes: 30
