name: Macos tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  macos:
    name: Mac Py${{ matrix.PYTHON_VERSION }}
    runs-on: macos-latest
    env:
      CI: True
      CODECOV_TOKEN: "a622d5af-356c-41f6-b298-b9b96f75be41"
      PYTHON_VERSION: ${{ matrix.PYTHON_VERSION }}
      RUNNER_OS: 'macos'
    strategy:
      fail-fast: false 
      matrix:
        PYTHON_VERSION: ['3.9']
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
           activate-environment: test
           auto-update-conda: false
           auto-activate-base: false
           python-version: ${{ matrix.PYTHON_VERSION }} 
           use-only-tar-bz2: true
           channels: conda-forge,defaults
           channel-priority: strict
           miniforge-variant: Mambaforge
      - name: Install package dependencies
        shell: bash -l {0}
        run: conda install --file requirements/conda.txt -y -q -c conda-forge
      - name: Install test dependencies
        shell: bash -l {0}
        run: |
          conda install nomkl -y -q
          conda install -c spyder-ide --file requirements/tests.txt -y -q
      - name: Install Package
        shell: bash -l {0}
        run: pip install --no-deps -e .
      - name: Show environment information
        shell: bash -l {0}
        run: |
          conda info
          conda list
      - name: Run tests
        shell: bash -l {0}
        run: python runtests.py
        timeout-minutes: 300
      - name: Coverages
        shell: bash -l {0}
        run: codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.14
